blank_issues_enabled: false
contact_links:
  - name: Yiğit Cemal Öztürk's Personal Mail Account
    url: mailto:ozturkyigitcemal@outlook.com.tr
    about: Please ask and answer questions here.
  - name: Yiğit Cemal Öztürk's Personal Mail Account
    url: mailto:ozturkyigitcemal@outlook.com.tr
    about: Please report security vulnerabilities here.
